# This file is automatically generated
echo "[process] starting client measure..."
gcloud compute ssh --ssh-key-file ~/.ssh/cloud-computing ubuntu@client-measure-73wb --zone europe-west3-a -- "cd memcache-perf-dynamic && ./mcperf -s 10.0.16.4 --loadonly"
gcloud compute ssh --ssh-key-file ~/.ssh/cloud-computing ubuntu@client-measure-73wb --zone europe-west3-a -- "cd memcache-perf-dynamic && ./mcperf -s 10.0.16.4 -a 10.0.16.2 --noload -T 16 -C 4 -D 4 -Q 1000 -c 4 -t 1800 --qps_interval 10 --qps_min 5000 --qps_max 100000"
