# This file is automatically generated
gcloud compute scp ./preloader.py ubuntu@memcache-server-vvdv:. --ssh-key-file ~/.ssh/cloud-computing --zone europe-west3-a
gcloud compute scp ./scheduler.py ubuntu@memcache-server-vvdv:. --ssh-key-file ~/.ssh/cloud-computing --zone europe-west3-a
gcloud compute scp ./4_scheduler_remote.sh ubuntu@memcache-server-vvdv:. --ssh-key-file ~/.ssh/cloud-computing --zone europe-west3-a
gcloud compute scp ./scheduler_logger.py ubuntu@memcache-server-vvdv:. --ssh-key-file ~/.ssh/cloud-computing --zone europe-west3-a
gcloud compute ssh --ssh-key-file ~/.ssh/cloud-computing ubuntu@memcache-server-vvdv --zone europe-west3-a
