# This file is automatically generated
pid=$(gcloud compute ssh --ssh-key-file ~/.ssh/cloud-computing ubuntu@memcache-server-gg32 --zone europe-west3-a --command "pgrep memcached")
echo "memcached pid is: $pid"
gcloud compute ssh --ssh-key-file ~/.ssh/cloud-computing ubuntu@memcache-server-gg32 --zone europe-west3-a --command "sudo taskset -a -cp 0-2 $pid"
gcloud compute ssh --ssh-key-file ~/.ssh/cloud-computing ubuntu@memcache-server-gg32 --zone europe-west3-a --command "sudo apt-get install python3-pip --yes"
gcloud compute ssh --ssh-key-file ~/.ssh/cloud-computing ubuntu@memcache-server-gg32 --zone europe-west3-a --command "sudo pip3 install docker"
gcloud compute ssh --ssh-key-file ~/.ssh/cloud-computing ubuntu@memcache-server-gg32 --zone europe-west3-a --command "sudo apt install docker.io"
gcloud compute ssh --ssh-key-file ~/.ssh/cloud-computing ubuntu@memcache-server-gg32 --zone europe-west3-a --command "grep docker /etc/group"
gcloud compute ssh --ssh-key-file ~/.ssh/cloud-computing ubuntu@memcache-server-gg32 --zone europe-west3-a --command "sudo usermod -aG docker ubuntu"
gcloud compute ssh --ssh-key-file ~/.ssh/cloud-computing ubuntu@memcache-server-gg32 --zone europe-west3-a --command "newgrp docker"
gcloud compute scp ./preloader.py ubuntu@memcache-server-gg32:. --ssh-key-file ~/.ssh/cloud-computing --zone europe-west3-a
gcloud compute ssh --ssh-key-file ~/.ssh/cloud-computing ubuntu@memcache-server-gg32 --zone europe-west3-a --command "python3 preloader.py"
gcloud compute scp ./scheduler.py ubuntu@memcache-server-gg32:. --ssh-key-file ~/.ssh/cloud-computing --zone europe-west3-a
gcloud compute ssh --ssh-key-file ~/.ssh/cloud-computing ubuntu@memcache-server-gg32 --zone europe-west3-a --command "python3 scheduler.py"
